
export const AppRoute = {
  HOME: '/',
  READER: '/reader/:suraId',
  STATS: '/stats',
  AI_CHAT: '/ai-chat'
};

export const SURA_LIST = [
  { id: 1, name: "الفاتحة", name_en: "Al-Fatihah", revelation_place: "Makkah", verses_count: 7 },
  { id: 2, name: "البقرة", name_en: "Al-Baqarah", revelation_place: "Madinah", verses_count: 286 },
  { id: 3, name: "آل عمران", name_en: "Ali 'Imran", revelation_place: "Madinah", verses_count: 200 },
  { id: 4, name: "النساء", name_en: "An-Nisa", revelation_place: "Madinah", verses_count: 176 },
  { id: 5, name: "المائدة", name_en: "Al-Ma'idah", revelation_place: "Madinah", verses_count: 120 },
  { id: 6, name: "الأنعام", name_en: "Al-An'am", revelation_place: "Makkah", verses_count: 165 },
  { id: 7, name: "الأعراف", name_en: "Al-A'raf", revelation_place: "Makkah", verses_count: 206 },
  { id: 8, name: "الأنفال", name_en: "Al-Anfal", revelation_place: "Madinah", verses_count: 75 },
  { id: 9, name: "التوبة", name_en: "At-Tawbah", revelation_place: "Madinah", verses_count: 129 },
  { id: 10, name: "يونس", name_en: "Yunus", revelation_place: "Makkah", verses_count: 109 },
  { id: 11, name: "هود", name_en: "Hud", revelation_place: "Makkah", verses_count: 123 },
  { id: 12, name: "يوسف", name_en: "Yusuf", revelation_place: "Makkah", verses_count: 111 },
  { id: 13, name: "الرعد", name_en: "Ar-Ra'd", revelation_place: "Madinah", verses_count: 43 },
  { id: 14, name: "إبراهيم", name_en: "Ibrahim", revelation_place: "Makkah", verses_count: 52 },
  { id: 15, name: "الحجر", name_en: "Al-Hijr", revelation_place: "Makkah", verses_count: 99 },
  { id: 16, name: "النحل", name_en: "An-Nahl", revelation_place: "Makkah", verses_count: 128 },
  { id: 17, name: "الإسراء", name_en: "Al-Isra", revelation_place: "Makkah", verses_count: 111 },
  { id: 18, name: "الكهف", name_en: "Al-Kahf", revelation_place: "Makkah", verses_count: 110 },
  { id: 19, name: "مريم", name_en: "Maryam", revelation_place: "Makkah", verses_count: 98 },
  { id: 20, name: "طه", name_en: "Ta-Ha", revelation_place: "Makkah", verses_count: 135 },
  { id: 21, name: "الأنبياء", name_en: "Al-Anbiya", revelation_place: "Makkah", verses_count: 112 },
  { id: 22, name: "الحج", name_en: "Al-Hajj", revelation_place: "Madinah", verses_count: 78 },
  { id: 23, name: "المؤمنون", name_en: "Al-Mu'minun", revelation_place: "Makkah", verses_count: 118 },
  { id: 24, name: "النور", name_en: "An-Nur", revelation_place: "Madinah", verses_count: 64 },
  { id: 25, name: "الفرقان", name_en: "Al-Furqan", revelation_place: "Makkah", verses_count: 77 },
  { id: 26, name: "الشعراء", name_en: "Ash-Shu'ara", revelation_place: "Makkah", verses_count: 227 },
  { id: 27, name: "النمل", name_en: "An-Naml", revelation_place: "Makkah", verses_count: 93 },
  { id: 28, name: "القصص", name_en: "Al-Qasas", revelation_place: "Makkah", verses_count: 88 },
  { id: 29, name: "العنكبوت", name_en: "Al-Ankabut", revelation_place: "Makkah", verses_count: 69 },
  { id: 30, name: "الروم", name_en: "Ar-Rum", revelation_place: "Makkah", verses_count: 60 },
  { id: 31, name: "لقمان", name_en: "Luqman", revelation_place: "Makkah", verses_count: 34 },
  { id: 32, name: "السجدة", name_en: "As-Sajdah", revelation_place: "Makkah", verses_count: 30 },
  { id: 33, name: "الأحزاب", name_en: "Al-Ahzab", revelation_place: "Madinah", verses_count: 73 },
  { id: 34, name: "سبإ", name_en: "Saba", revelation_place: "Makkah", verses_count: 54 },
  { id: 35, name: "فاطر", name_en: "Fatir", revelation_place: "Makkah", verses_count: 45 },
  { id: 36, name: "يس", name_en: "Ya-Sin", revelation_place: "Makkah", verses_count: 83 },
  { id: 37, name: "الصافات", name_en: "As-Saffat", revelation_place: "Makkah", verses_count: 182 },
  { id: 38, name: "ص", name_en: "Sad", revelation_place: "Makkah", verses_count: 88 },
  { id: 39, name: "الزمر", name_en: "Az-Zumar", revelation_place: "Makkah", verses_count: 75 },
  { id: 40, name: "غافر", name_en: "Ghafir", revelation_place: "Makkah", verses_count: 85 },
  { id: 41, name: "فصلت", name_en: "Fussilat", revelation_place: "Makkah", verses_count: 54 },
  { id: 42, name: "الشورى", name_en: "Ash-Shura", revelation_place: "Makkah", verses_count: 53 },
  { id: 43, name: "الزخرف", name_en: "Az-Zukhruf", revelation_place: "Makkah", verses_count: 89 },
  { id: 44, name: "الدخان", name_en: "Ad-Dukhan", revelation_place: "Makkah", verses_count: 59 },
  { id: 45, name: "الجاثية", name_en: "Al-Jathiyah", revelation_place: "Makkah", verses_count: 37 },
  { id: 46, name: "الأحقاف", name_en: "Al-Ahqaf", revelation_place: "Makkah", verses_count: 35 },
  { id: 47, name: "محمد", name_en: "Muhammad", revelation_place: "Madinah", verses_count: 38 },
  { id: 48, name: "الفتح", name_en: "Al-Fath", revelation_place: "Madinah", verses_count: 29 },
  { id: 49, name: "الحجرات", name_en: "Al-Hujurat", revelation_place: "Madinah", verses_count: 18 },
  { id: 50, name: "ق", name_en: "Qaf", revelation_place: "Makkah", verses_count: 45 },
  { id: 51, name: "الذاريات", name_en: "Adh-Dhariyat", revelation_place: "Makkah", verses_count: 60 },
  { id: 52, name: "الطور", name_en: "At-Tur", revelation_place: "Makkah", verses_count: 49 },
  { id: 53, name: "النجم", name_en: "An-Najm", revelation_place: "Makkah", verses_count: 62 },
  { id: 54, name: "القمر", name_en: "Al-Qamar", revelation_place: "Makkah", verses_count: 55 },
  { id: 55, name: "الرحمن", name_en: "Ar-Rahman", revelation_place: "Madinah", verses_count: 78 },
  { id: 56, name: "الواقعة", name_en: "Al-Waqi'ah", revelation_place: "Makkah", verses_count: 96 },
  { id: 57, name: "الحديد", name_en: "Al-Hadid", revelation_place: "Madinah", verses_count: 29 },
  { id: 58, name: "المجادلة", name_en: "Al-Mujadila", revelation_place: "Madinah", verses_count: 22 },
  { id: 59, name: "الحشر", name_en: "Al-Hashr", revelation_place: "Madinah", verses_count: 24 },
  { id: 60, name: "الممتحنة", name_en: "Al-Mumtahanah", revelation_place: "Madinah", verses_count: 13 },
  { id: 61, name: "الصف", name_en: "As-Saff", revelation_place: "Madinah", verses_count: 14 },
  { id: 62, name: "الجمعة", name_en: "Al-Jumu'ah", revelation_place: "Madinah", verses_count: 11 },
  { id: 63, name: "المنافقون", name_en: "Al-Munafiqun", revelation_place: "Madinah", verses_count: 11 },
  { id: 64, name: "التغابن", name_en: "At-Taghabun", revelation_place: "Madinah", verses_count: 18 },
  { id: 65, name: "الطلاق", name_en: "At-Talaq", revelation_place: "Madinah", verses_count: 12 },
  { id: 66, name: "التحريم", name_en: "At-Tahrim", revelation_place: "Madinah", verses_count: 12 },
  { id: 67, name: "الملك", name_en: "Al-Mulk", revelation_place: "Makkah", verses_count: 30 },
  { id: 68, name: "القلم", name_en: "Al-Qalam", revelation_place: "Makkah", verses_count: 52 },
  { id: 69, name: "الحاقة", name_en: "Al-Haqqah", revelation_place: "Makkah", verses_count: 52 },
  { id: 70, name: "المعارج", name_en: "Al-Ma'arij", revelation_place: "Makkah", verses_count: 44 },
  { id: 71, name: "نوح", name_en: "Nuh", revelation_place: "Makkah", verses_count: 28 },
  { id: 72, name: "الجن", name_en: "Al-Jinn", revelation_place: "Makkah", verses_count: 28 },
  { id: 73, name: "المزمل", name_en: "Al-Muzzammil", revelation_place: "Makkah", verses_count: 20 },
  { id: 74, name: "المدثر", name_en: "Al-Muddathir", revelation_place: "Makkah", verses_count: 56 },
  { id: 75, name: "القيامة", name_en: "Al-Qiyamah", revelation_place: "Makkah", verses_count: 40 },
  { id: 76, name: "الإنسان", name_en: "Al-Insan", revelation_place: "Madinah", verses_count: 31 },
  { id: 77, name: "المرسلات", name_en: "Al-Mursalat", revelation_place: "Makkah", verses_count: 50 },
  { id: 78, name: "النبأ", name_en: "An-Naba", revelation_place: "Makkah", verses_count: 40 },
  { id: 79, name: "النازعات", name_en: "An-Nazi'at", revelation_place: "Makkah", verses_count: 46 },
  { id: 80, name: "عبس", name_en: "Abasa", revelation_place: "Makkah", verses_count: 42 },
  { id: 81, name: "التكوير", name_en: "At-Takwir", revelation_place: "Makkah", verses_count: 29 },
  { id: 82, name: "الانفطار", name_en: "Al-Infitar", revelation_place: "Makkah", verses_count: 19 },
  { id: 83, name: "المطففين", name_en: "Al-Mutaffifin", revelation_place: "Makkah", verses_count: 36 },
  { id: 84, name: "الانشقاق", name_en: "Al-Inshiqaq", revelation_place: "Makkah", verses_count: 25 },
  { id: 85, name: "البروج", name_en: "Al-Buruj", revelation_place: "Makkah", verses_count: 22 },
  { id: 86, name: "الطارق", name_en: "At-Tariq", revelation_place: "Makkah", verses_count: 17 },
  { id: 87, name: "الأعلى", name_en: "Al-A'la", revelation_place: "Makkah", verses_count: 19 },
  { id: 88, name: "الغاشية", name_en: "Al-Ghashiyah", revelation_place: "Makkah", verses_count: 26 },
  { id: 89, name: "الفجر", name_en: "Al-Fajr", revelation_place: "Makkah", verses_count: 30 },
  { id: 90, name: "البلد", name_en: "Al-Balad", revelation_place: "Makkah", verses_count: 20 },
  { id: 91, name: "الشمس", name_en: "Ash-Shams", revelation_place: "Makkah", verses_count: 15 },
  { id: 92, name: "الليل", name_en: "Al-Layl", revelation_place: "Makkah", verses_count: 21 },
  { id: 93, name: "الضحى", name_en: "Ad-Duha", revelation_place: "Makkah", verses_count: 11 },
  { id: 94, name: "الشرح", name_en: "Ash-Sharh", revelation_place: "Makkah", verses_count: 8 },
  { id: 95, name: "التين", name_en: "At-Tin", revelation_place: "Makkah", verses_count: 8 },
  { id: 96, name: "العلق", name_en: "Al-Alaq", revelation_place: "Makkah", verses_count: 19 },
  { id: 97, name: "القدر", name_en: "Al-Qadr", revelation_place: "Makkah", verses_count: 5 },
  { id: 98, name: "البينة", name_en: "Al-Bayyinah", revelation_place: "Madinah", verses_count: 8 },
  { id: 99, name: "الزلزلة", name_en: "Az-Zalzalah", revelation_place: "Madinah", verses_count: 8 },
  { id: 100, name: "العاديات", name_en: "Al-Adiyat", revelation_place: "Makkah", verses_count: 11 },
  { id: 101, name: "القارعة", name_en: "Al-Qari'ah", revelation_place: "Makkah", verses_count: 11 },
  { id: 102, name: "التكاثر", name_en: "At-Takathur", revelation_place: "Makkah", verses_count: 8 },
  { id: 103, name: "العصر", name_en: "Al-Asr", revelation_place: "Makkah", verses_count: 3 },
  { id: 104, name: "الهمزة", name_en: "Al-Humazah", revelation_place: "Makkah", verses_count: 9 },
  { id: 105, name: "الفيل", name_en: "Al-Fil", revelation_place: "Makkah", verses_count: 5 },
  { id: 106, name: "قريش", name_en: "Quraysh", revelation_place: "Makkah", verses_count: 4 },
  { id: 107, name: "الماعون", name_en: "Al-Ma'un", revelation_place: "Makkah", verses_count: 7 },
  { id: 108, name: "الكوثر", name_en: "Al-Kawthar", revelation_place: "Makkah", verses_count: 3 },
  { id: 109, name: "الكافرون", name_en: "Al-Kafirun", revelation_place: "Makkah", verses_count: 6 },
  { id: 110, name: "النصر", name_en: "An-Nasr", revelation_place: "Madinah", verses_count: 3 },
  { id: 111, name: "المسد", name_en: "Al-Masad", revelation_place: "Makkah", verses_count: 5 },
  { id: 112, name: "الإخلاص", name_en: "Al-Ikhlas", revelation_place: "Makkah", verses_count: 4 },
  { id: 113, name: "الفلق", name_en: "Al-Falaq", revelation_place: "Makkah", verses_count: 5 },
  { id: 114, name: "الناس", name_en: "An-Nas", revelation_place: "Makkah", verses_count: 6 }
];

export const DEFAULT_TRANSLATIONS = [
  { key: 'english_saheeh', title: 'Saheeh International', language: 'English' },
  { key: 'english_hilali_khan', title: 'Hilali & Khan', language: 'English' },
  { key: 'french_montada', title: 'Montada Islamic Association', language: 'French' },
  { key: 'spanish_garcia', title: 'Muhammad Isa García', language: 'Spanish' },
  { key: 'indonesian_complex', title: 'Kemenag RI', language: 'Indonesian' },
];

export const COLOR_PALETTE = {
  primary: '#064e3b',
  secondary: '#d97706',
  accent: '#fef3c7',
  text: '#1e293b',
  lightText: '#64748b',
};
